const learned = "口人一二山三心十零四五六七八九日月大太木水火土士子父牛馬马川林森竹雨夕門门刀舟車车炮入中上下前西北古令之百天金母卒象名伙仕後東东南今止亡家男女分年豕力安豬猪肉円儿兒丁小国國不乙玉目毛犬猫貓";
const learning = "左右存無无有友平萬万千因見见全午白字個固足个箇來来先光行出去往了彳亍主坐帝內外工君苦失兄姉妹飲魚弟漢品半耳手生学校本每何貝贝氣气米高低文明神申新多少長早來食立書言飲話語間聞休時週道会社花電";
const chars = [
"制@chế@chế ngự, thể chế, chế độ",
"製@chế@chế tạo",
"支@chi@chi nhánh, chi trì (ủng hộ)",
"志@chí@ý chí, chí nguyện",
"誌@chí@tạp chí",
"指@chỉ@chỉ định, chỉ số",
"止@chỉ@đình chỉ",
"紙@chỉ@giấy",
"占@chiêm, chiếm@chiếm cứ",
"戦@chiến@chiến tranh, chiến đấu",
"折@chiết@bẻ gãy, chiết suất",
"招@chiêu@chiêu đãi",
"昭@chiêu@sáng",
"政@chính@chính phủ, chính sách, hành chính",
"正@chính@chính đáng, chính nghĩa, chân chính",
"整@chỉnh@điều chỉnh, chỉnh hình",
"株@chu@cổ phiếu",
"周@chu@chu vi, chu biên",
"週@chu@tuần",
"注@chú@chú ý, chú thích",
"主@chủ@chủ yếu, chủ nhân",
"諸@chư@chư hầu",
"準@chuẩn@tiêu chuẩn, chuẩn bị",
"織@chức@dệt",
"職@chức@chức vụ, từ chức",
"終@chung@chung kết, chung liễu",
"衆@chúng@quần chúng, chúng sinh",
"種@chủng@chủng loại, chủng tộc",
"症@chứng@chứng bệnh, triệu chứng",
"証@chứng@bằng chứng, nhân chứng, chứng nhận",
"章@chương@chương sách",
"障@chướng@chướng ngại",
"専@chuyên@chuyên môn, chuyên quyền",
"転@chuyển@chuyển động",
"固@cố@ngoan cố, cố thủ",
"故@cố@cố tổng thống, lí do",
"雇@cố@thuê, cố nông",
"顧@cố@nhìn lại",
"基@cơ@cơ sở, cơ bản",
"機@cơ@cơ khí, thời cơ, phi cơ",
"古@cổ@cũ, cổ điển, đồ cổ",
"谷@cốc@thung lũng, khê cốc",
"公@công@công cộng, công thức, công tước",
"功@công@công lao",
"工@công@công tác, công nhân",
"攻@công@tấn công, công kích",
"共@cộng@tổng cộng, cộng sản, công cộng",
"骨@cốt@xương, cốt nhục",
"居@cư@cư trú",
"具@cụ@công cụ, dụng cụ",
"拠@cứ@căn cứ, chiếm cứ",
"挙@cử@tuyển cử, cử động, cử hành",
"巨@cự@to lớn, cự đại, cự phách",
"拒@cự@cự tuyệt",
"局@cục@cục diện, cục kế hoạch",
"極@cực@cực lực, cùng cực, địa cực",
"宮@cung@cung điện",
"供@cung@cung cấp, cung phụng",
"強@cường, cưỡng@cường quốc; miễn cưỡng",
"救@cứu@cấp cứu, cứu trợ",
"究@cứu@nghiên cứu, cứu cánh",
"久@cửu@lâu, vĩnh cửu",
"九@cửu@9",
"旧@cựu@cũ, cựu thủ tướng, cựu binh",
"野@dã@cánh đồng, hoang dã, thôn dã",
"夜@dạ@ban đêm, dạ cảnh, dạ quang",
"多@đa@đa số",
"打@đả@đả kích, ẩu đả",
"得@đắc@đắc lợi, cầu bất đắc",
"特@đặc@đặc biệt, đặc công",
"台@đài@lâu đài, đài",
"待@đãi@đợi, đối đãi",
"逮@đãi@đuổi bắt",
"代@đại@đại biểu, thời đại, đại diện, đại thế",
"大@đại@to lớn, đại dương, đại lục",
"談@đàm@hội đàm, đàm thoại",
"担@đảm@đảm đương, đảm bảo",
"民@dân@quốc dân, dân tộc",
"引@dẫn@dẫn hỏa",
"弾@đàn, đạn@đánh đàn; viên đạn",
"様@dạng@đa dạng, hình dạng",
"登@đăng@trèo, đăng sơn, đăng kí, đăng lục",
"党@đảng@đảng phái",
"等@đẳng@bình đẳng, đẳng cấp",
"名@danh@danh tính, địa danh",
"逃@đào@đào tẩu",
"倒@đảo@đảo lộn",
"島@đảo@hải đảo",
"導@đạo@dẫn đường, chỉ đạo",
"道@đạo@đạo lộ, đạo đức, đạo lí",
"答@đáp@trả lời, vấn đáp, đáp ứng",
"踏@đạp@dẫm lên",
"達@đạt@đạt tới, điều đạt, thành đạt",
"闘@đấu@đấu tranh, chiến đấu",
"投@đầu@đầu tư, đầu cơ",
"頭@đầu@đầu não",
"低@đê@thấp, đê hèn, đê tiện",
"締@đế@buộc",
"題@đề@đề tài, đề mục, chủ đề",
"提@đề@cung cấp, đề cung",
"悪@ác, ố@hung ác, độc ác; tăng ố",
"愛@ái@yêu, ái tình, ái mộ",
"音@âm@âm thanh, phát âm",
"安@an@an bình, an ổn",
"印@ấn@in ấn, ấn tượng",
"英@anh@anh hùng, anh tú, anh tuấn",
"映@ánh@phản ánh",
"影@ảnh@hình ảnh; nhiếp ảnh",
"奥@áo@trong cùng",
"圧@áp@áp lực, trấn áp",
"押@áp@ấn",
"欧@âu@châu âu",
"波@ba@sóng, phong ba",
"博@bác@uyên bác",
"北@bắc@phương bắc",
"迫@bách@áp bách, bức bách",
"百@bách@trăm, bách niên",
"白@bạch@thanh bạch, bạch sắc",
"敗@bại@thất bại",
"半@bán@bán cầu, bán nguyệt",
"盤@bàn@cái khay",
"板@bản@tấm bảng",
"版@bản@xuất bản",
"本@bản@sách, cơ bản, nguyên bản, bản chất",
"伴@bạn@đi cùng",
"般@bàn, ban@nhất ban",
"邦@bang@liên bang",
"崩@băng@băng hoại",
"浜@banh@bờ biển",
"報@báo@báo cáo, báo thù, báo đáp",
"抱@bão@ôm, hoài bão",
"保@bảo@bảo trì, bảo vệ, đảm bảo",
"暴@bạo, bộc@bạo lực, bộc lộ",
"八@bát@8",
"不@bất@bất công, bất bình đẳng, bất tài",
"抜@bạt@rút ra",
"閉@bế@bế mạc, bế quan",
"病@bệnh@bệnh nhân, bệnh viện, bệnh tật",
"彼@bỉ@anh ta",
"被@bị@bị, bị động, bị cáo",
"備@bị@trang bị, phòng bị, thiết bị",
"編@biên@đan, biên tập",
"辺@biên@biên, biên giới",
"変@biến@biến đổi, biến thiên",
"弁@biện@hùng biện, biện luận",
"別@biệt@biệt li, đặc biệt, tạm biệt",
"表@biểu@biểu hiện, bảng biểu, biểu diễn",
"兵@binh@binh lính, binh lực",
"評@bình@bình luận, phê bình",
"平@bình@hòa bình, bình đẳng, trung bình, bình thường",
"補@bổ@bổ sung, bổ túc",
"部@bộ@bộ môn, bộ phận",
"捕@bộ@bắt, đãi bộ",
"歩@bộ@bộ hành, tiến bộ",
"爆@bộc@bộc phát",
"背@bối@bối cảnh",
"倍@bội@bội thu, bội số",
"郵@bưu@bưu điện",
"歌@ca@ca dao, ca khúc",
"各@các@các, mỗi",
"閣@các@nội các",
"格@cách@tư cách, cách thức, sở hữu cách",
"革@cách@da thuộc, cách mạng",
"改@cải@cải cách, cải chính",
"禁@cấm@cấm đoán, nghiêm cấm",
"感@cảm@cảm giác, cảm xúc, cảm tình",
"幹@cán@cán sự, cán bộ",
"筋@cân@gân cơ",
"根@căn@gốc, căn bản, căn cứ",
"勤@cần@chuyên cần, cần lao",
"近@cận@thân cận, cận thị, cận cảnh",
"港@cảng@hải cảng, không cảng",
"更@canh@canh tân",
"境@cảnh@nhập cảnh, quá cảnh, cảnh ngộ",
"景@cảnh@cảnh sắc, thắng cảnh, quang cảnh",
"警@cảnh@cảnh báo, cảnh sát, cảnh vệ",
"競@cạnh@cạnh tranh",
"高@cao@cao đẳng, cao thượng",
"告@cáo@báo cáo, thông cáo",
"急@cấp@khẩn cấp, cấp cứu",
"級@cấp@sơ cấp, trung cấp, cao cấp",
"給@cấp@cung cấp, cấp phát",
"及@cập@phổ cập",
"割@cát@chia cắt, cát cứ",
"吉@cát@tốt lành, cát tường",
"詰@cật@đóng hộp",
"構@cấu@cấu tạo, cấu thành, cơ cấu",
"購@cấu@mua",
"求@cầu@yêu cầu, mưu cầu",
"球@cầu@quả cầu, địa cầu",
"針@châm@cái kim, phương châm, châm cứu",
"真@chân@chân lí, chân thực",
"振@chấn@chấn động",
"震@chấn@địa chấn",
"執@chấp@cố chấp",
"質@chất@vật chất, phẩm chất, khí chất",
"州@châu@tỉnh, bang, châu lục",
"底@để@đáy",
"第@đệ@đệ nhất, đệ nhị",
"移@di@di chuyển, di động",
"遺@di@sót lại, di tích, di ngôn, di vật",
"以@dĩ@dĩ tiền, dĩ vãng",
"異@dị@dị bản, dị tộc, dị giáo",
"易@dị, dịch@dễ, dịch chuyển",
"地@địa@thổ địa, địa đạo",
"駅@dịch@ga",
"役@dịch@chức vụ, nô dịch",
"訳@dịch@thông dịch, phiên dịch",
"的@đích@mục đích, đích thực",
"店@điếm@cửa hàng, tửu điếm",
"点@điểm@điểm số, điểm hỏa",
"演@diễn@diễn viên, biểu diễn, diễn giả",
"面@diện@phản diện, chính diện",
"田@điền@điền viên, tá điền",
"典@điển@cổ điển, điển tích",
"殿@điện@cung điện",
"電@điện@phát điện, điện lực",
"葉@diệp@lá, lạc diệp, hồng diệp",
"曜@diệu@ngày trong tuần",
"条@điều@điều khoản, điều kiện",
"鳥@điểu@chim chóc",
"調@điều, điệu@điều tra, điều hòa; thanh điệu, giai điệu",
"丁@đinh@can thứ 4 trong 天干, trai tráng",
"町@đinh@khu phố",
"停@đình@đình chỉ",
"庭@đình@triều đình, gia đình",
"定@định@thiết định, quyết định, định mệnh",
"由@do@tự do, lí do",
"都@đô@đô thị, đô thành",
"図@đồ@bản đồ, đồ án, địa đồ",
"徒@đồ@môn đồ, đồ đệ",
"途@đồ@tiền đồ",
"渡@độ@đi qua, truyền tay",
"度@độ@mức độ, quá độ, độ lượng",
"端@đoan@đầu đoạn",
"団@đoàn@đoàn kết, đoàn đội",
"短@đoản@đoản mệnh, sở đoản",
"段@đoạn@giai đoạn",
"断@đoạn, đoán@phán đoán, đoạn tuyệt",
"営@doanh@doanh nghiệp, kinh doanh, doanh trại",
"奪@đoạt@chiếm đoạt",
"督@đốc@giám đốc, đôn đốc",
"独@độc@cô độc, đơn độc",
"読@độc@độc giả, độc thư",
"対@đối@đối diện, phản đối, đối với",
"帯@đới@nhiệt đới, ôn đới",
"隊@đội@đội ngũ, quân đội",
"単@đơn@cô đơn, đơn độc, đơn chiếc",
"東@đông@phía đông",
"同@đồng@đồng nhất, tương đồng",
"働@động@lao động",
"動@động@hoạt động, chuyển động",
"突@đột@đột phá, đột nhiên",
"油@du@dầu",
"遊@du@du hí, du lịch",
"余@dư@thặng dư, dư dật",
"裕@dụ@giàu sang",
"誘@dụ@dụ dỗ",
"予@dự@dự đoán, dự báo",
"預@dự@gửi",
"与@dữ, dự@cấp dữ, tham dự",
"育@dục@giáo dục, dưỡng dục",
"欲@dục@dục vọng",
"徳@đức@đạo đức",
"融@dung@tan chảy, dung hòa, dung hợp",
"容@dung@dung mạo, hình dung, nội dung, dung nhận",
"用@dụng@sử dụng, dụng cụ, công dụng",
"薬@dược@thuốc",
"躍@dược@nhảy lên",
"洋@dương@đại dương, tây dương",
"陽@dương@thái dương",
"養@dưỡng@dưỡng dục",
"堂@đường@thực đường, thiên đường",
"当@đương, đáng@chính đáng; đương thời, tương đương",
"維@duy@sợi dây",
"延@duyên@trì hoãn",
"加@gia@tăng gia, gia giảm",
"家@gia@gia đình, chuyên gia",
"価@giá@giá cả, vô giá, giá trị",
"者@giả@học giả, tác giả",
"覚@giác@cảm giác, giác ngộ",
"角@giác@tam giác, tứ giác",
"階@giai@giai cấp, giai tầng",
"解@giải@giải quyết, giải thể, giải thích",
"減@giảm@gia giảm, giảm",
"監@giam, giám@giam cấm; giám đốc, giám sát",
"間@gian@trung gian, không gian",
"簡@giản@đơn giản",
"江@giang@trường giang, giang hồ",
"講@giảng@giảng đường, giảng bài",
"降@giáng, hàng@giáng trần; đầu hàng",
"交@giao@giao hảo, giao hoán",
"教@giáo@giáo dục, giáo viên",
"介@giới@ở giữa, môi giới, giới thiệu",
"界@giới@thế giới, giới hạn, địa giới",
"届@giới@đưa đến",
"何@hà@cái gì, hà cớ",
"河@hà@sông, sơn hà",
"下@hạ@dưới, hạ đẳng",
"夏@hạ@mùa hè",
"賀@hạ@chúc mừng",
"黒@hắc@đen, hắc ám",
"核@hạch@hạt nhân, hạch tâm",
"海@hải@hải cảng, hải phận",
"害@hại@có hại, độc hại, lợi hại",
"含@hàm@hàm ý, hàm nghĩa, hàm súc",
"限@hạn@giới hạn, hữu hạn, hạn độ",
"航@hàng@hàng không, hàng hải",
"項@hạng@hạng mục",
"幸@hạnh@hạnh phúc, hạnh vận",
"行@hành, hàng@thực hành, lữ hành; ngân hàng",
"豪@hào@hào kiệt, phú hào",
"好@hảo, hiếu@hữu hảo; hiếu sắc",
"後@hậu@sau, hậu quả, hậu sự",
"候@hậu@mùa, khí hậu, thời hậu",
"厚@hậu@nồng hậu, hậu tạ",
"係@hệ@quan hệ, hệ số",
"系@hệ@hệ thống, hệ số",
"希@hi@hi hữu, hi vọng",
"喜@hỉ@vui",
"険@hiểm@nguy hiểm, mạo hiểm, hiểm ác",
"憲@hiến@hiến pháp, hiến binh",
"献@hiến@hiến dâng, hiến tặng, hiến thân",
"現@hiện@xuất hiện, hiện tại, hiện tượng, hiện hình",
"協@hiệp@hiệp lực",
"効@hiệu@hiệu quả, hiệu ứng, công hiệu",
"校@hiệu@trường học",
"号@hiệu@phiên hiệu, tín hiệu, phù hiệu",
"刑@hình@hình phạt, tử hình",
"型@hình@khuôn hình, mô hình",
"形@hình@hình thức, hình hài, định hình",
"呼@hô@gọi tên, hô hoán, hô hấp, hô hào",
"互@hỗ@tương hỗ",
"戸@hộ@hộ khẩu",
"護@hộ@bảo hộ, phòng hộ, hộ vệ",
"花@hoa@hoa, bông hoa",
"化@hóa@biến hóa",
"貨@hóa@hàng hóa",
"和@hòa@hòa bình, tổng hòa, điều hòa",
"火@hỏa@lửa",
"画@họa, hoạch@họa sĩ; kế hoạch",
"惑@hoặc@nghi hoặc",
"壊@hoại@phá hoại",
"完@hoàn@hoàn thành, hoàn toàn",
"環@hoàn@hoàn cảnh, tuần hoàn",
"還@hoàn@hoàn trả",
"丸@hoàn@tròn",
"緩@hoãn@hòa hoãn",
"患@hoạn@bệnh hoạn",
"皇@hoàng@hoàng đế",
"横@hoành@tung hoành, hoành độ, hoành hành",
"活@hoạt@hoạt động, sinh hoạt",
"学@học@học sinh, học thuyết",
"回@hồi@vu hồi, chương hồi",
"会@hội@hội họp, đại hội",
"絵@hội@hội họa",
"婚@hôn@kết hôn, hôn nhân",
"混@hỗn@hỗn hợp, hỗn độn, hỗn loạn",
"合@hợp@thích hợp, hội họp, hợp lí",
"許@hứa@cho phép, hứa khả",
"恵@huệ@ân huệ",
"雄@hùng@thư hùng, anh hùng, hùng tráng",
"興@hưng, hứng@hưng thịnh, phục hưng; hứng thú",
"況@huống@tình huống, trạng huống",
"香@hương@mùi hương, hương thơm",
"向@hướng@hướng thượng, phương hướng",
"響@hưởng@ảnh hưởng, âm hưởng",
"休@hưu@hưu trí, hưu nhàn",
"右@hữu@bên phải, hữu ngạn, cánh hữu",
"友@hữu@bạn hữu, hữu hảo",
"有@hữu@sở hữu, hữu hạn",
"揮@huy@phát huy, chỉ huy",
"懸@huyền@treo",
"県@huyện@huyện, tỉnh",
"血@huyết@tâm huyết",
"益@ích@lợi ích, hữu ích",
"継@kế@kế tục",
"計@kê, kế@thống kê; kế hoạch, kế toán",
"結@kết@đoàn kết, kết thúc",
"可@khả@có thể, khả năng, khả dĩ",
"刻@khắc@thời khắc",
"客@khách@hành khách, thực khách",
"開@khai@khai mạc, khai giảng",
"緊@khẩn@khẩn cấp, khẩn trương",
"康@khang@kiện khang, khang trang",
"考@khảo@khảo sát, tư khảo",
"口@khẩu@miệng, nhân khẩu, khẩu ngữ",
"契@khế@khế ước",
"崎@khi@mũi đất",
"器@khí@khí cụ, cơ khí, dung khí",
"棄@khí@từ bỏ",
"気@khí@không khí, khí chất, khí khái, khí phách",
"欠@khiếm@khiếm khuyết",
"遣@khiển@phân phát",
"軽@khinh@khinh suất, khinh khi",
"庫@khố@kho, xa khố, kim khố",
"苦@khổ@khổ cực, cùng khổ",
"科@khoa@khoa học, chuyên khoa",
"課@khóa@khóa học, chính khóa",
"券@khoán@vé, chứng khoán",
"起@khởi@khởi động, khởi sự, khởi nghĩa",
"困@khốn@khốn cùng",
"空@không@không khí, hư không, hàng không",
"控@khống@khống chế",
"区@khu@khu vực, địa khu",
"去@khứ@đi, quá khứ, trừ khử; khứ niên: năm ngoái; đối với lai 來",
"曲@khúc@ca khúc",
"拡@khuếch@khuếch đại",
"恐@khủng@khủng bố, khủng hoảng",
"却@khước@khước từ",
"傾@khuynh@khuynh đảo, khuynh hướng",
"記@kí@thư kí, kí sự, kí ức",
"期@kì@thời kì, kì hạn",
"技@kĩ@kĩ thuật, kĩ nghệ",
"紀@kỉ@thế kỉ, kỉ nguyên",
"撃@kích@công kích, tập kích",
"激@kích@kích động, kích thích, kích hoạt",
"劇@kịch@kịch bản, vở kịch, kịch tính",
"検@kiểm@kiểm tra",
"建@kiến@kiến thiết, kiến tạo",
"見@hiện, kiến@(见) hiện ra, chứng kiến, ý kiến, thấy",
"件@kiện@điều kiện, sự kiện, bưu kiện",
"健@kiện@khỏe mạnh, kiện khang, tráng kiện",
"橋@kiều@cây cầu",
"金@kim@hoàng kim, kim ngân",
"今@kim@đương kim, kim nhật",
"京@kinh@kinh đô, kinh thành",
"経@kinh@kinh tế, sách kinh, kinh độ",
"敬@kính@kính yêu",
"絡@lạc@liên lạc",
"落@lạc@rơi, lạc hạ, trụy lạc",
"楽@lạc, nhạc@an lạc, lạc thú, âm nhạc",
"来@lai@đến, tương lai, vị lai",
"瀬@lại@thác nước",
"頼@lại@ỷ lại",
"林@lâm@lâm sản, lâm nghiệp",
"臨@lâm@lâm thời",
"冷@lãnh@lạnh, lãnh đạm",
"労@lao@lao động, lao lực, công lao",
"老@lão@già, lão luyện",
"立@lập@thiết lập, tự lập",
"戻@lệ@quay lại",
"例@lệ@ví dụ, tiền lệ, thông lệ, điều lệ",
"令@lệnh@mệnh lệnh, pháp lệnh",
"離@li@tách li, li khai",
"理@lí@lí do, lí luận, nguyên lí",
"裏@lí@đằng sau",
"里@lí@làng",
"歴@lịch@lí lịch, lịch sử, kinh lịch",
"連@liên@liên tục, liên lạc",
"列@liệt@cột, la liệt",
"僚@liêu@đồng liêu, quan liêu",
"了@liễu@kết liễu, liễu giải",
"料@liệu@nguyên liệu, tài liệu, nhiên liệu",
"療@liệu@trị liệu",
"鈴@linh@cái chuông",
"齢@linh@tuổi",
"領@lĩnh, lãnh@thống lĩnh, lãnh thổ, lĩnh vực",
"路@lộ@đường, không lộ, thủy lộ",
"類@loại@chủng loại",
"湾@loan@vịnh",
"乱@loạn@phản loạn, chiến loạn",
"利@lợi@phúc lợi, lợi ích",
"隆@long@cao quý",
"旅@lữ@lữ hành, lữ khách",
"慮@lự@tư lự, khảo lự",
"輪@luân@bánh xe, luân hồi",
"論@luận@lí luận, ngôn luận, thảo luận",
"律@luật@luật pháp",
"陸@lục@lục địa, lục quân",
"六@lục@6",
"録@lục@kí lục, đăng lục",
"力@lực@sức lực",
"略@lược@tỉnh lược, xâm lược",
"良@lương@tốt, lương tâm, lương tri",
"両@lưỡng@hai, lưỡng quốc",
"量@lượng@lực lượng, độ lượng, dung lượng, trọng lượng",
"流@lưu@lưu lượng, hạ lưu, lưu hành",
"留@lưu@lưu học, lưu trữ",
"塁@lũy@thành lũy",
"練@luyện@rèn luyện, luyện tập",
"馬@mã@ngựa",
"幕@mạc@khai mạc, bế mạc",
"枚@mai@tờ",
"買@mãi@mua, khuyến mãi",
"売@mại@thương mại",
"満@mãn@thỏa mãn, bất mãn, mãn nguyện",
"末@mạt@kết thúc, mạt vận, mạt kì",
"密@mật@bí mật, mật độ",
"母@mẫu@mẹ, phụ mẫu, mẫu thân",
"貿@mậu@mậu dịch, trao đổi",
"迷@mê@mê hoặc, mê đắm",
"米@mễ@gạo",
"命@mệnh, mạng@tính mạng, cách mạng, vận mệnh, mệnh lệnh",
"美@mĩ@mĩ nhân, mĩ lệ",
"描@miêu@miêu tả",
"秒@miểu@giây (1/60 phút)",
"明@minh@quang minh, minh tinh",
"盟@minh@đồng minh, gia minh",
"模@mô@mô phỏng, mô hình",
"募@mộ@mộ tập, chiêu mộ",
"暮@mộ@chiều tối",
"木@mộc@cây, gỗ",
"毎@mỗi@mỗi",
"門@môn@cửa, nhập môn, môn đồ, bộ môn",
"夢@mộng@mơ",
"目@mục@mắt, hạng mục, mục lục",
"男@nam@đàn ông, nam giới",
"南@nam@phương nam",
"難@nan, nạn@khó, nan giải, nguy nan; tai nạn",
"能@năng@năng lực, tài năng",
"脳@não@bộ não, đầu não",
"納@nạp@nộp",
"我@ngã@bản ngã",
"額@ngạch@trán, giá tiền, hạn ngạch, kim ngạch",
"銀@ngân@ngân hàng, ngân lượng, kim ngân",
"岸@ngạn@hải ngạn",
"芸@nghệ@nghệ thuật, nghệ nhân",
"迎@nghênh@hoan nghênh, nghênh tiếp",
"儀@nghi@nghi thức",
"疑@nghi@nghi ngờ, nghi vấn, tình nghi",
"議@nghị@nghị luận, nghị sự",
"義@nghĩa@ý nghĩa, nghĩa lí, đạo nghĩa",
"逆@nghịch@phản nghịch",
"厳@nghiêm@tôn nghiêm, nghiêm khắc, nghiêm trọng",
"験@nghiệm@thí nghiệm, hiệu nghiệm, kinh nghiệm",
"研@nghiên@mài, nghiên cứu",
"業@nghiệp@nghề nghiệp, công nghiệp, sự nghiệp",
"午@ngọ@chính ngọ",
"外@ngoại@ngoài, ngoại thành, ngoại đạo",
"玉@ngọc@ngọc",
"言@ngôn@ngôn ngữ, ngôn luận, phát ngôn",
"五@ngũ@5",
"語@ngữ@ngôn ngữ, từ ngữ",
"危@nguy@nguy hiểm, nguy cơ",
"元@nguyên@gốc",
"原@nguyên@thảo nguyên, nguyên tử, nguyên tắc",
"源@nguyên@nguồn, nguyên tuyền",
"願@nguyện@tự nguyện, tình nguyện",
"月@nguyệt@mặt trăng, tháng, nguyệt san, nguyệt thực",
"街@nhai@phố xá",
"岩@nham@đá tảng, nham thạch",
"賃@nhẫm@tiền thuê",
"顔@nhan@nhan sắc, hồng nhan",
"因@nhân@nguyên nhân",
"人@nhân@nhân vật",
"認@nhận@xác nhận, nhận thức",
"入@nhập@nhập cảnh, nhập môn, nhập viện",
"一@nhất@một, đồng nhất, nhất định",
"日@nhật@mặt trời, ngày, nhật thực, nhật báo",
"児@nhi@nhi đồng, hài nhi",
"二@nhị@2",
"染@nhiễm@ô nhiễm",
"任@nhiệm@trách nhiệm, nhiệm vụ",
"然@nhiên@quả nhiên, tất nhiên, thiên nhiên",
"燃@nhiên@nhiên liệu",
"熱@nhiệt@nhiệt độ, nhiệt tình",
"需@nhu@nhu yếu",
"肉@nhục@thịt",
"若@nhược@trẻ, nhược niên",
"弱@nhược@nhược điểm, nhược tiểu",
"念@niệm@ý niệm, tưởng niệm",
"年@niên@năm, niên đại",
"努@nỗ@nỗ lực",
"内@nội@nội thành, nội bộ",
"農@nông@nông nghiệp, nông thôn, nông dân",
"女@nữ@phụ nữ",
"汚@ô@ô nhiễm",
"屋@ốc@phòng ốc",
"温@ôn@ôn hòa, ôn tồn",
"破@phá@phá hoại, tàn phá",
"派@phái@trường phái",
"品@phẩm@sản phẩm",
"犯@phạm@phạm nhân",
"判@phán@phán quyết, phán đoán",
"販@phán@bán, phán mại",
"分@phân@phân số, phân chia",
"坂@phản@cái dốc",
"反@phản@phản loạn, phản đối",
"返@phản@trả lại",
"法@pháp@pháp luật, phương pháp",
"発@phát@xuất phát, phát kiến, phát hiện, phát ngôn",
"払@phất@trả tiền",
"仏@phật@phật giáo",
"批@phê@phê bình, phê phán",
"廃@phế@tàn phế, hoang phế",
"非@phi@phi nhân đạo, phi nghĩa",
"飛@phi@bay, phi công, phi hành",
"費@phí@học phí, lộ phí, chi phí",
"番@phiên@thứ tự, phiên hiệu",
"票@phiếu@lá phiếu, đầu phiếu",
"副@phó@phó, phó phòng",
"浦@phổ@cửa biển",
"普@phổ@phổ thông",
"配@phối@phân phối, chi phối, phối ngẫu",
"風@phong@phong ba, phong cách, phong tục",
"豊@phong@phong phú",
"放@phóng@giải phóng, phóng hỏa, phóng lao",
"房@phòng@phòng ở",
"防@phòng@phòng vệ, phòng bị, đề phòng",
"訪@phóng, phỏng@phóng sự; phỏng vấn",
"夫@phu@trượng phu, phu phụ",
"富@phú@giàu, phú hào, phú hộ, phong phú",
"浮@phù@nổi, phù du",
"否@phủ@phủ định, phủ quyết",
"付@phụ@phụ thuộc, phụ lục",
"婦@phụ@phụ nữ, dâm phụ",
"父@phụ@phụ tử, phụ thân, phụ huynh",
"負@phụ@âm, mang, phụ thương, phụ trách",
"幅@phúc@bề ngang",
"福@phúc@phúc, hạnh phúc, phúc lợi",
"復@phục@phục thù, hồi phục",
"服@phục@y phục, cảm phục, phục vụ",
"複@phức@phức tạp",
"方@phương@phương hướng, phương pháp",
"果@quả@hoa quả, thành quả, kết quả",
"過@qua, quá@thông qua; quá khứ, quá độ",
"掛@quải@treo",
"官@quan@quan lại",
"観@quan@quan sát, tham quan",
"関@quan@hải quan, quan hệ",
"館@quán@đại sứ quán, hội quán",
"均@quân@quân bình, quân nhất",
"君@quân@quân chủ, quân vương",
"軍@quân@quân đội, quân sự",
"群@quần@quần chúng, quần thể",
"管@quản@ống, mao quản, quản lí",
"光@quang@ánh sáng, nhật quang, quang minh",
"広@quảng@quảng trường, quảng đại",
"国@quốc@(國) nước, quốc gia, quốc ca",
"帰@quy@hồi quy",
"規@quy@quy tắc, quy luật",
"季@quý@mùa",
"貴@quý@cao quý",
"権@quyền@chính quyền, quyền uy, quyền lợi",
"巻@quyển@quyển sách",
"決@quyết@quyết định",
"色@sắc@màu sắc, sắc dục",
"策@sách@đối sách",
"差@sai@sai khác, sai biệt",
"杉@sam@cây sam",
"森@sâm@rừng",
"刊@san@tuần san, chuyên san",
"産@sản@sản xuất, sinh sản, cộng sản",
"創@sáng@sáng tạo",
"庁@sảnh@đại sảnh",
"渋@sáp@chát",
"察@sát@quan sát, giám sát, cảnh sát",
"殺@sát@sát hại, sát nhân",
"仕@sĩ@làm việc",
"士@sĩ@chiến sĩ, sĩ tử, bác sĩ",
"超@siêu@siêu việt, siêu thị, siêu nhân",
"生@sinh@sinh sống, sinh sản",
"数@số@số lượng",
"初@sơ@sơ cấp",
"所@sở@trụ sở",
"山@sơn@núi, sơn hà",
"師@sư@giáo sư, tôn sư trọng đạo",
"史@sử@lịch sử, sử sách",
"事@sự@sự việc",
"使@sử, sứ@sử dụng; sứ giả, thiên sứ",
"率@suất@thống suất, xác suất, tỉ lệ suất",
"縮@súc@co lại",
"捜@sưu@sưu tầm, sưu tập",
"佐@tá@phò tá, trợ tá",
"借@tá@mượn, tá điền",
"左@tả@bên trái, tả hữu, cánh tả",
"写@tả@miêu tả",
"作@tác@tác phẩm, công tác, canh tác",
"則@tắc@quy tắc, phép tắc",
"昨@tạc@qua, qua..",
"災@tai@tai họa",
"再@tái@lại, tái phát",
"裁@tài@may vá, tài phán, trọng tài",
"材@tài@tài liệu",
"財@tài@tiền tài, tài sản",
"載@tải@đăng tải",
"在@tại@tồn tại, thực tại",
"三@tam@3",
"心@tâm@tâm lí, nội tâm",
"暫@tạm@tạm thời",
"賛@tán@tán đồng, tán thành",
"残@tàn@tàn dư, tàn tích, tàn đảng",
"新@tân@mới, cách tân, tân thời",
"津@tân@bờ biển",
"散@tán, tản@phấn tán, tản mát",
"葬@táng@an táng",
"蔵@tàng@bảo tàng, tàng trữ, tàng hình",
"増@tăng@tăng gia, tăng tốc",
"層@tầng@hạ tầng, thượng tầng",
"贈@tặng@hiến tặng",
"早@tảo@sớm, tảo hôn",
"造@tạo@chế tạo, sáng tạo",
"雑@tạp@tạp chí, tạp kĩ",
"習@tập@học tập",
"集@tập@tập hợp, tụ tập",
"秘@tất@tất nhiên, tất yếu",
"必@tất@tất nhiên, tất yếu",
"奏@tấu@diễn tấu",
"走@tẩu@chạy",
"西@tây@phương tây",
"済@tế@kinh tế, cứu tế",
"細@tế@tinh tế, tường tế, tế bào",
"際@tế@quốc tế",
"他@tha@khác, tha hương, vị tha",
"託@thác@ủy thác",
"石@thạch@đá, thạch anh, bảo thạch",
"太@thái@thái dương, thái bình",
"態@thái@trạng thái, hình thái, thái độ",
"採@thải@hái, thải dụng",
"貸@thải@cho mượn",
"参@tham@tham chiếu, tham quan, tham khảo",
"探@thám@do thám, thám hiểm",
"深@thâm@thâm sâu, thâm hậu",
"審@thẩm@thẩm tra, thẩm phán, thẩm định",
"伸@thân@dãn ra",
"申@thân@thân thỉnh (xin)",
"親@thân@thân thuộc, thân thích, thân thiết",
"身@thân@thân thể, thân phận",
"神@thần@thần, thần thánh, thần dược",
"慎@thận@thận trọng",
"昇@thăng@thăng tiến, thăng thiên",
"勝@thắng@thắng lợi, thắng cảnh",
"縄@thằng@sợi dây",
"清@thanh@thanh bạch, trong sạch",
"声@thanh@âm thanh, thanh điệu",
"青@thanh@xanh, thanh thiên, thanh niên",
"城@thành@thành phố, thành quách",
"成@thành@thành tựu, hoàn thành, trở thành",
"草@thảo@thảo mộc",
"討@thảo@thảo phạt, thảo luận, kiểm thảo",
"十@thập@mười",
"七@thất@7",
"失@thất@thất nghiệp, thất bại",
"室@thất@phòng, giáo thất",
"輸@thâu@thâu nhập, thâu xuất",
"妻@thê@thê tử",
"世@thế@thế giới, thế gian, thế sự",
"勢@thế@tư thế, thế lực",
"替@thế@thay thế, đại thế",
"体@thể@hình thể, thân thể, thể thao",
"施@thi@thực thi, thi hành",
"試@thí@thí nghiệm, thí điểm",
"市@thị@thành thị, thị trường",
"氏@thị@họ",
"視@thị@thị sát, thị lực, giám thị",
"示@thị@biểu thị",
"適@thích@thích hợp",
"千@thiên@nghìn, nhiều, thiên lí",
"天@thiên@thiên thạch, thiên nhiên, thiên đường",
"善@thiện@thiện ác, từ thiện",
"渉@thiệp@can thiệp, giao thiệp",
"切@thiết@cắt, thiết thực, thân thiết",
"設@thiết@thiết lập, kiến thiết",
"鉄@thiết@sắt, thiết đạo, thiết giáp",
"焼@thiêu@thiêu đốt",
"紹@thiệu@giới thiệu",
"少@thiếu, thiểu@thiếu niên; thiểu số",
"聴@thính@thính giả",
"請@thỉnh@thỉnh cầu, thỉnh nguyện",
"盛@thịnh@thịnh vượng, hưng thịnh",
"措@thố@đặt, để",
"土@thổ@thổ địa, thổ công",
"妥@thỏa@thỏa hiệp",
"退@thoái@triệt thoái, thoái lui",
"話@thoại@nói chuyện, đối thoại, giai thoại",
"脱@thoát@giải thoát",
"催@thôi@tổ chức, khai thôi, thôi thúc",
"推@thôi@giới thiệu, thôi tiến",
"時@thời@thời gian",
"村@thôn@thôn xã, thôn làng",
"通@thông@thông qua, thông hành, phổ thông",
"痛@thống@thống khổ",
"統@thống@thống nhất, tổng thống, thống trị",
"収@thu@thu nhập, thu nhận, thu hoạch",
"秋@thu@mùa thu",
"取@thủ@lấy, nhận",
"守@thủ@cố thủ, bảo thủ",
"手@thủ@tay, thủ đoạn",
"首@thủ@đầu, cổ, thủ tướng",
"書@thư@thư đạo, thư tịch, thư kí",
"受@thụ@nhận, tiếp thụ",
"授@thụ@đưa cho, truyền thụ, giáo thụ",
"樹@thụ@cây, cổ thụ",
"次@thứ@thứ nam, thứ nữ",
"承@thừa@thừa nhận",
"乗@thừa@lên xe",
"純@thuần@đơn thuần, thuần khiết",
"順@thuận@tòng thuận, thuận tự",
"術@thuật@kĩ thuật, học thuật, nghệ thuật",
"述@thuật@tường thuật. tự thuật",
"束@thúc@bó (hoa)",
"式@thức@hình thức, phương thức, công thức",
"識@thức@nhận thức, kiến thức, tri thức",
"実@thực@sự thực, chân thực",
"張@trương@chủ trương, khai trương",
"場@trường@hội trường, quảng trường",
"長@trường, trưởng@trường giang, sở trường; hiệu trưởng",
"追@truy@truy lùng, truy nã, truy cầu",
"伝@truyền, truyện@truyền đạt, truyền động; tự truyện",
"修@tu@tu sửa, tu chính, tu luyện",
"秀@tú@ưu tú, tuấn tú",
"姿@tư@tư thế, tư dung, tư sắc",
"思@tư@nghĩ, suy tư, tư tưởng, tư duy",
"私@tư@tư nhân, công tư, tư lợi",
"資@tư@tư bản, đầu tư, tư cách",
"四@tứ@4",
"辞@từ@từ vựng, từ chức",
"子@tử@tử tôn, phần tử, phân tử, nguyên tử",
"死@tử@tử thi, tự tử",
"字@tự@chữ, văn tự",
"寺@tự@chùa",
"自@tự@tự do, tự kỉ, tự thân",
"緒@tự@tình tự",
"旬@tuần@10 ngày",
"宿@túc@tá túc, kí túc xá",
"足@túc@chân, bổ túc, sung túc",
"続@tục@tiếp tục",
"息@tức@con trai, tử tức",
"歳@tuế@tuổi, năm, tuế nguyệt",
"従@tùng@phục tùng, tùy tùng, tòng thuận",
"松@tùng@cây tùng, tùng bách",
"削@tước@gọt, tước đoạt",
"将@tướng@tướng quân",
"想@tưởng@tư tưởng, tưởng tượng",
"象@tượng@hiện tượng, khí tượng, hình tượng",
"像@tượng@tưởng tượng, thần tượng",
"相@tương, tướng@tương hỗ, tương tự, tương đương; thủ tướng",
"酒@tửu@rượu",
"就@tựu@thành tựu",
"宣@tuyên@tuyên bố, tuyên cáo",
"線@tuyến@dây, tiền tuyến, điện tuyến, vô tuyến",
"選@tuyển@tuyển chọn",
"絶@tuyệt@đoạn tuyệt, tuyệt diệu",
"億@ức@trăm triệu",
"抑@ức@ức chế",
"応@ứng@đáp ứng, ứng đối, phản ứng",
"約@ước@lời hứa (ước nguyện), ước tính",
"央@ương@trung ương",
"優@ưu@ưu việt, ưu thế, ưu tiên",
"委@ủy@ủy viên, ủy ban, ủy thác",
"文@văn@văn chương, văn học",
"聞@văn@nghe, tân văn (báo)",
"問@vấn@vấn đáp, chất vấn, vấn đề",
"万@vạn@vạn, nhiều, vạn vật",
"運@vận@vận chuyển, vận mệnh",
"物@vật@động vật",
"衛@vệ@bảo vệ, vệ tinh, vệ sinh",
"囲@vi@chu vi, bao vây",
"違@vi@vi phạm, tương vi",
"尾@vĩ@cái đuôi",
"位@vị@vị trí, tước vị, đơn vị",
"味@vị@vị giác, mùi vị",
"未@vị@vị thành niên, vị lai",
"為@vi, vị@hành vi; vị kỉ",
"員@viên@thành viên, nhân viên",
"円@viên@viên mãn, tiền Yên",
"園@viên@vườn, điền viên, hoa viên, công viên",
"遠@viễn@viễn phương, vĩnh viễn",
"院@viện@học viện, y viện",
"援@viện@viện trợ",
"越@việt@vượt qua, việt vị",
"栄@vinh@vinh quang, vinh hạnh",
"永@vĩnh@vĩnh viễn, vỉnh cửu",
"無@vô@hư vô, vô ý nghĩa",
"亡@vong@diệt vong",
"望@vọng@ước vọng, nguyện vọng, kì vọng",
"宇@vũ@vũ trụ",
"羽@vũ@lông vũ",
"雨@vũ@mưa",
"武@vũ@vũ trang, vũ lực",
"舞@vũ@vũ điệu, khiêu vũ",
"務@vụ@chức vụ, nhiệm vụ",
"域@vực@khu vực, lĩnh vực",
"王@vương@vương giả",
"車@xa@xe cộ, xa lộ",
"社@xã@xã hội, công xã, hợp tác xã",
"射@xạ@xạ thủ",
"確@xác@chính xác, xác lập, xác suất",
"企@xí@xí nghiệp, xí hoạch",
"赤@xích@đỏ, xích kì, xích đạo, xích thập tự",
"処@xử, xứ@cư xử, xử trí, xử lí; nơi chỗ",
"春@xuân@mùa xuân, thanh xuân",
"出@xuất@xuất hiện, xuất phát",
"触@xúc@tiếp xúc",
"促@xúc@xúc tiến",
"沖@xung@ngoài khơi",
"称@xưng@xưng tên, danh xưng",
"川@xuyên@sông",
"医@y@y học, y viện",
"意@ý@ý nghĩa, ý thức, ý kiến, chú ý",
"依@ỷ@ỷ lại",
"掲@yết@yết thị",
"要@yêu, yếu@yêu cầu; chủ yếu",
"食@thực@ẩm thực, thực đường",
"税@thuế@thuế vụ",
"属@thuộc@phụ thuộc",
"傷@thương@tổn thương, thương tật",
"商@thương@thương mại, thương số",
"倉@thương@nhà kho",
"償@thường@bồi thường",
"常@thường@bình thường, thông thường",
"賞@thưởng@giải thưởng, tưởng thưởng",
"上@thượng@thượng tầng, thượng đẳng",
"始@thủy@ban đầu, khai thủy, nguyên thủy",
"水@thủy@thủy điện",
"船@thuyền@thuyền",
"説@thuyết@tiểu thuyết, học thuyết, lí thuyết",
"比@tỉ@so sánh, tỉ lệ, tỉ dụ",
"避@tị@tị nạn",
"司@ti, tư@công ti, tư lệnh",
"積@tích@tích tụ, súc tích, tích phân",
"績@tích@thành tích",
"跡@tích@dấu tích, vết tích",
"席@tịch@chủ tịch, xuất tịch (tham gia)",
"夕@tịch@tịch dương",
"先@tiên@tiên sinh, tiên tiến",
"鮮@tiên@sáng, tươi, tiên minh (tươi đẹp), tân tiên",
"進@tiến@thăng tiến, tiền tiến, tiến lên",
"銭@tiền@tiền bạc",
"前@tiền@trước, tiền sử, tiền chiến, mặt tiền",
"便@tiện@thuận tiện",
"接@tiếp@nối tiếp, tiếp đãi, tiếp xúc",
"節@tiết@tiết mục",
"消@tiêu@tiêu diệt, tiêu hao, tiêu thất",
"標@tiêu@mục tiêu, tiêu chuẩn",
"笑@tiếu@cười",
"小@tiểu@nhỏ, ít",
"信@tín@uy tín, tín thác, thư tín",
"星@tinh@hành tinh, tinh tú",
"精@tinh@tinh lực, tinh túy",
"性@tính@tính dục, giới tính, bản tính, tính chất",
"併@tính@thôn tính",
"情@tình@tình cảm, tình thế",
"静@tĩnh@bình tĩnh, trấn tĩnh",
"井@tỉnh@giếng",
"省@tỉnh@tỉnh lược, phản tỉnh, hồi tỉnh",
"並@tịnh@xếp hàng",
"素@tố@yếu tố, nguyên tố",
"訴@tố@tố cáo, tố tụng",
"組@tổ@tổ hợp, tổ chức",
"座@tọa@chỗ ngồi, tọa đàm, tọa độ",
"算@toán@tính toán, kế toán, toán học",
"全@toàn@toàn bộ",
"速@tốc@tốc độ, tăng tốc",
"族@tộc@gia tộc, dân tộc, chủng tộc",
"最@tối@nhất (tối cao, tối đa)",
"罪@tội@tội phạm, tội ác",
"宗@tôn@tôn giáo",
"存@tồn@tồn tại, bảo tồn, ôn tồn",
"損@tổn@tổn hại, tổn thương",
"送@tống@tiễn, tống tiễn, tống đạt",
"総@tổng@tổng số, tổng cộng",
"卒@tốt@tốt nghiệp",
"査@tra@điều tra",
"側@trắc@bên cạnh",
"測@trắc@đo đạc",
"責@trách@khiển trách, trách cứ, trách nhiệm",
"宅@trạch@nhà ở",
"択@trạch@tuyển trạch",
"沢@trạch@đầm lầy",
"債@trái@nợ, quốc trái, công trái",
"陣@trận@trận mạc",
"装@trang@trang phục, hóa trang, trang bị",
"状@trạng@tình trạng, trạng thái, cáo trạng",
"争@tranh@đấu tranh, chiến tranh, tranh luận, cạnh tranh",
"扱@tráp@đối xử",
"札@trát@tiền giấy",
"知@tri@tri thức, tri giác",
"置@trí@bố trí, bài trí, vị trí",
"致@trí@trí mạng",
"持@trì@cầm, duy trì",
"池@trì@cái ao",
"遅@trì@muộn",
"治@trị@cai trị, trị an, trị bệnh",
"値@trị@giá trị",
"摘@trích@hái, trích yếu",
"展@triển@triển khai, phát triển, triển lãm",
"撤@triệt@triệt thoái",
"朝@triều@buổi sáng, triều đình",
"兆@triệu@triệu chứng, triệu triệu (10 mũ 12)",
"程@trình@trình độ, lộ trình, công trình",
"助@trợ@hộ trợ, trợ giúp, viện trợ, cứu trợ",
"仲@trọng@trọng tài",
"重@trọng, trùng@trọng lượng; trùng phùng",
"著@trứ@trứ danh, trứ tác",
"除@trừ@trừ khử, trừ bỏ, loại trừ, phép chia",
"住@trú, trụ@cư trú; trụ sở",
"築@trúc@kiến trúc",
"竹@trúc@trúc",
"直@trực@trực tiếp, chính trực",
"中@trung@trung tâm, trung gian, trung ương",
"塚@trủng@đống đất",
"徴@trưng@đặc trưng, tượng trưng",
"零@linh@số không, lẻ, mưa lác đác",
"牛@ngưu@bò: hoàng ngưu, trâu: thủy ngưu",
"门@môn@cửa",
"刀@đao@đao kiếm",
"舟@chu@thuyền",
"东@đông@phía đông",
"之@chi@đã, rồi, thuộc về, mà, là",
"无@vô@hư vô, vô ý nghĩa",
"马@mã@ngựa",
"车@xa@xe cộ, xa lộ",
"伙@hỏa, lõa@đồng hỏa: đồng bạn, đồng lõa",
"炮@pháo@pháo, mìn",
"豕@thỉ@con heo, ít dùng hơn trư 豬",
"豬@trư@(豬) con heo, thông dụng hơn thỉ 豕",
"猪@trư@(豬) con heo, thông dụng hơn thỉ 豕",
"萬@vạn@(万) mười ngàn, 10000",
"见@hiện, kiến@(見) hiện ra, chứng kiến, ý kiến, thấy",
"儿@nhi, nhân@(兒) trẻ con, nhi đồng, 儿 là nhân đi, 人 là nhân nằm",
"兒@nhi@(儿) trẻ con, nhi đồng, 儿 là nhân đi, 人 là nhân nằm",
"國@quốc@(国) quốc gia",
"乙@ất@can thứ 2 trong 天干, ruột",
"毛@mao, mô@lông vũ",
"犬@khuyển@chó",
"猫@miêu@(貓) mèo",
"貓@miêu@(猫) mèo",
"个@cá@(箇, 個) cá biệt, cá thể",
"箇@cá@(个, 個) cá biệt, cá thể",
"來@lai@đến, đến nay, về sau; lai niên: năm sau; đối với khứ 去, vãng 往",
"個@cá@(个, 箇 ) cá biệt, cá thể",
"往@vãng@đi, đã qua; vãng lai 往來: đi lại",
"彳@xích@bước chân trái, bước ngắn, bộ xích",
"亍@xúc@bước chân phải, ngừng bước",
"坐@tọa@ngồi, đi xe, buộc tội",
"帝@đế@vua, thượng đế",
"內@nội, nạp@bên trong, thu vào, giao nộp",
"兄@huynh@anh trai",
"姉@tỉ@chị gái",
"妹@muội@em gái",
"飲@ẩm@uống, đồ uống",
"魚@ngư@cá",
"弟@đệ@em trai",
"漢@hán@chữ hán, người Trung Quốc",
"耳@nhĩ@tai",
"每@mỗi@mỗi một",
"貝@bối@(貝) sò, hến, vật quý, tiền",
"贝@bối@(貝) sò, hến, vật quý, tiền",
"氣@khí@(气) không khí, hơi",
"气@khí@(氣) không khí, hơi"
];